FAS.Web/Controllers/HomeController.cs
namespace FAS.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Diagnostics;
    using System.Collections.Generic;

    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using FAS.Web.Models;
    using FAS.Services.Contracts;
    using FAS.Services.Models;
    using FAS.Web.Models.HomeViewModels;

    [Authorize]
    public class HomeController : Controller
    {
        private const int pageSize = 10;
        private const int page = 1;

        private readonly ISportService sportService;
        private readonly IUserService userService;

        public HomeController(ISportService sportService, IUserService userService)
        {
            this.sportService = sportService;
            this.userService = userService;
        }

        public async Task<IActionResult> Index() => View(await this.sportService.AllActiveAsync());

        public IActionResult Search(string search)
        {
            var users = this.userService.AllWithBlocked();

            if (!string.IsNullOrWhiteSpace(search))
            {
                users = users.Where(s => s.FirstName.ToLower().Contains(search.ToLower()));

            }

            return View(new HomeIndexUserPagingModel
            {
                Users = users.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                Search = search,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(users.Count() / (double)pageSize)
            });
        }

        public IActionResult About()
        {
            ViewData["Message"] = "sechko about.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "sechko contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FAS.Web/Controllers/SportController.cs
namespace FAS.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Authorization;

    using FAS.Data.Models;
    using FAS.Services.Contracts;
    using FAS.Services.Models;
    using FAS.Web.Infrastructure;
    using FAS.Web.Infrastructure.Extensions;
    using FAS.Web.Models.Sports;
    

  
    public class SportController : Controller
    {
        private const int PageSize = 25;
        private const string UsersView = "Members";

        private readonly ISportService sportService;
        private readonly UserManager<User> userManager;

        public SportController(ISportService sportService, UserManager<User> userManager)
        {
            this.sportService = sportService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return this.View();
        }


        public async Task<IActionResult> Details(int id)
        {
            var model = new SportDetailsViewModel
            {
                Sport = await this.sportService.ByIdAsync<SportDetailsServiceModel>(id),
                TraiUsersnings = await this.sportService.UsersInSport(id)
            };

            if (model.Sport == null)
            {
                return this.NotFound();
            }

            if (this.User.Identity.IsAuthenticated)
            {
                var userId = this.userManager.GetUserId(this.User);

                model.IsUserEnrolledInSport = await this.sportService.IsUserSignedInSportAsync(id, userId);
            }

            return this.View(model);
        }

        [Authorize(Roles = WebConstants.AdministratorRole)]
        public async Task<IActionResult> Create()
        {
            return View(new AddSportFormModel
            {
                StartDate = DateTime.UtcNow,
                EndDate = DateTime.UtcNow.AddDays(20),
                Trainers = await GetTrainers()
            });
        }

        [HttpPost]
        [Authorize(Roles = WebConstants.AdministratorRole)]
        public async Task<IActionResult> Create(AddSportFormModel model)
        {
            var user = await this.userManager.FindByIdAsync(model.TrainerId);
            if (user == null)
            {
                this.ModelState.AddModelError(string.Empty, "Invalid user.");
            }

            if (!this.ModelState.IsValid)
            {
                model.Trainers = await GetTrainers();
                return View(model);
            }

            await this.sportService.Create(
                model.Name,
                model.Description,
                model.StartDate,
                model.EndDate,
                model.TrainerId);

            this.TempData.AddSuccessMessage("Sport created successfully.");

            return this.RedirectToAction(
                nameof(HomeController.Index),
                "Home",
                routeValues: new { area = string.Empty });
        }
         
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SignUpUser(int id)
        {
            var userId = this.userManager.GetUserId(this.User);
            var success = await this.sportService.SignUpUserAsync(id, userId);

            if (!success)
            {
                return BadRequest();
            }

            this.TempData.AddSuccessMessage("You successfully enrolled in this sport.");

            return this.RedirectToAction(nameof(Details), new { id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SignOutUser(int id)
        {
            var userId = this.userManager.GetUserId(this.User);
            var success = await this.sportService.SignOutUserAsync(id, userId);

            if (!success)
            {
                return BadRequest();
            }

            this.TempData.AddSuccessMessage("You successfully signed out of this sport.");

            return this.RedirectToAction(nameof(Details), new { id });
        }

        private async Task<IEnumerable<SelectListItem>> GetTrainers()
        {
            var trainers = await this.userManager.GetUsersInRoleAsync(WebConstants.TrainerRole);
            return trainers
                 .Select(t => new SelectListItem
                 {
                     Text = $"{t.FirstName} ({t.LastName})",
                     Value = t.Id
                 })
                 .OrderBy(t => t.Text)
                 .ToList();
        }

    }
}

FAS.Web/Controllers/UsersController.cs
namespace FAS.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Authorization;

    using FAS.Services.Contracts;
    using FAS.Services.Models;

    using FAS.Web.Models;
    using FAS.Web.Models.Users;
    using FAS.Web.Infrastructure;
    using FAS.Web.Infrastructure.Extensions;

    using FAS.Data.Models;
    using FAS.Web.Infrastructure.Filters;

    [Authorize(Roles =  WebConstants.AdministratorRole)]
    public class UsersController : Controller
    {
        private const int PageSize = 10;
        private const string UsersView = "Members";

        private readonly IUserService userService;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public UsersController(IUserService userService, RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            this.userService = userService;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [ResponseCache(Duration = 60 * 12)]
        public async Task<IActionResult> Index()
        {
            var users = await this.userService.AllAsync();

            var roles = await this.roleManager
                .Roles
                .OrderBy(r => r.Name)
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name 
                })
                .ToListAsync();

            return this.View(new UserListingViewModel
            {
                Users = users.OrderBy(u => u.FirstName).ThenBy(u => u.LastName),
                Roles = roles
            });
        }

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> AddToRole(AddUserToRoleFormModel model)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);
            var userExists = user != null;

            if (!roleExists || !userExists)
            {
                this.ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!this.ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            await this.userManager.AddToRoleAsync(user, model.Role);

            this.TempData.AddSuccessMessage($"User {user.UserName} added to role {model.Role}");

            return RedirectToAction(nameof(Index));
        }

        
        public IActionResult All(int page = 1)
             => View(new UserPageListModel()
             {
                 Users = this.userService.All(page, PageSize),
                 CurrentPage = page,
                 TotalPages = (int)Math.Ceiling(this.userService.UserCount() / (double)PageSize)
             });

        public IActionResult Registration()
        {
            ViewData["Add new mamber"] = "Add new mamber page";

            return View();
        }
        
        [Route("gander/{id:int:min(1)}")]
        public IActionResult Gander(int id)
        {
            return View("All", new UserPageListModel()
            {
                Users = this.userService.SortByGander(id, 1, PageSize),
                CurrentPage = 1,
                TotalPages = (int)Math.Ceiling(this.userService.UserCount() / (double)PageSize)
            });
        }

        public IActionResult Blocked()
        {
            return View("All", new UserPageListModel()
            {
                Users = this.userService.BlockedUsers(WebConstants.StartPage, WebConstants.PageSize),
                CurrentPage = WebConstants.StartPage,
                TotalPages = (int)Math.Ceiling(this.userService.UserCount() / (double)PageSize)
            });
        }

        [Route("profile/{id:int:min(1)}")]
        public IActionResult Profile(string id)
        {
            var user = this.userService.UserById(id);
            if (user == null)
            {
                return NotFound();
            }

            ViewData["Title"] = $"{user.FirstName} {user.LastName} Details";

            return View("Profile", user);
        }

        public IActionResult Edit(string id)
        {
            var user = this.userService.UserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        public IActionResult NotPaidYet()
        {
            return View(new UserPageListModel()
            {
                Users = this.userService.NotPaid(WebConstants.StartPage, WebConstants.PageSize),
                CurrentPage = WebConstants.StartPage,
                TotalPages = (int)Math.Ceiling(this.userService.UserCount() / (double)PageSize)
            });
        }

        [HttpPost]
        [ValidateModelState]
        public IActionResult Edit(UserDetailsModel user)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(user);
            //}

            this.userService.Edit(user);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FAS.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FAS.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div class="col-lg-offset-2">
    <h2>@ViewData["Title"]</h2>
    <address>
        <strong>Location </strong> <span>Bulgaria, Sofia</span>&nbsp; &nbsp;
        <strong>Phone:</strong> <span>+359 899 750 224</span><br />
        <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a>&nbsp; &nbsp;
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>


    <img alt="Come on" src="~/images/Accessdenied2.gif" width="800" height="411">
</div> 

FAS.Web/Views/Home/Index.cshtml
@model IEnumerable<SportListingServiceModel>

<br />
<h1 class="col-lg-offset-4">All Active Sport Groups</h1><br />
<div class="container-fluid col-md-12">


    <div class="col-md-12">

        <div class="row home-page">
            @foreach (var sport in Model)
            {
                <div class="col-md-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <a asp-controller="Sport"
                                   asp-action=@(nameof(SportController.Details))
                                   asp-route-id=@sport.Id>@sport.Name</a>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <h4 class="text-muted text-center">@sport.StartDate.ToShortDateString() - @sport.EndDate.ToShortDateString()</h4>
                            <h5 class="text-muted text-center">Coach: @sport.Trainer</h5>
                            <div class="col-md-4">
                                <img class="img-circle img-responsive" src="~/@sport.UserPhoto" asp-append-version="true" />
                            </div>
                            <br />
                            <div >@sport.Description</div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FAS.Web/Views/Home/Search.cshtml
@model HomeIndexUserPagingModel
@{
    ViewData["Title"] = "All fitness members";
}
@{
    var previousDisabled = Model.CurrentPage == 1 ? "disabled" : string.Empty;
    var nextDisabled = Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty;

}

<br /><br />
     
<h3> User Search</h3>

<form method="get" class="search-form" style="width: 225px;">
    <div class="form-group has-feedback">
        <label for="search" class="sr-only">Search</label>
        <input type="text" class="form-control" name="search" id="search" placeholder="Search + Enter" value="@Model.Search" />
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
    </div>
</form>
    

<table class="table-bordered table-hover table-responsive col-md-12">
    <thead>
        <tr>
            <th class="col-md-1">
                Photo
            </th>
            <th class="col-md-1">
                Name & Gander
            </th>
            <th class="col-md-1">
                Date, Mail, Phone
            </th>
            <th class="col-md-2">
                Adress
            </th>
            <th class="col-md-1">
                Member
            </th>
            <th class="col-md-1">
                Proof
            </th>
            <th class="col-md-1">
                Age
            </th>
            <th class="col-md-1">
                Pay
            </th>
            <th class="col-md-1">
                Star
            </th>
            <th class="col-md-1">
                Block
            </th>
            @if (User.IsInRole("Administrator"))
            {
                <th class="col-md-1">
                    Modify
                </th>
            }
            </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
        <tr>
            <td width="150" height="170">
                <a asp-controller="Users" asp-action="Profile" asp-route-id="@user.Id">
                    <img src="~/@user.UserPhoto" asp-append-version="true" width="150" height="170" />
                </a>
            </td>



            <td class="col-md-1">
                @if (user.IsStarMember)
                {<img src="~/images/5-stars.png" width="90" height="30" />}
                @user.FirstName  <br /> @user.LastName <br /><br />
                @user.Sex
            </td>

            <td class="col-md-1">
                @user.Date <br /><br />
                @user.Email <br /><br />
                @user.PhoneNumber
            </td>

            <td class="col-md-2">
                @user.Adress
            </td>

            <td class="col-md-1">
                @user.MembershipType

            <td class="col-md-1">
                @user.ProofGiven
            </td>

            <td class="col-md-1">
                @user.Age
            </td>

            <td class="col-md-1">
                @user.IsPayed
            </td>

            <td class="col-md-1">
                @user.IsStarMember
            </td>

            <td class="col-md-1">
                @user.IsBlocked
            </td>

            @if (User.IsInRole("Administrator"))
            {
                <td class="col-md-1">
                    <a class="btn btn-warning btn-sm" href="/users/edit/@user.Id">Edit</a>
                </td>
            }
            </tr>

        }
    </tbody>
</table>

<div class="text-center">
    <ul class="pagination">
        <li class="page-item @previousDisabled">
            <a class="page-link @previousDisabled" href="/users/all?page=@Model.PreviousPage" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(Model.CurrentPage == i ? "active" : string.Empty)"><a class="page-link" href="/home/search?page=@i">@i</a></li>
        }
        <li class="page-item @nextDisabled">
            <a class="page-link @nextDisabled" href="/home/search?page=@Model.NextPage" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</div>